### ISSUE TITLE
Mock camera Loaded

### ISSUE THREAD

**Issue by Farghal1** [beniroquai/ImSwitchConfig#8]
Hello,

I kept trying to make the camera work with imswitch, but I still get the same warning and the mock camera is loaded.

I'm using Allied Vision Camera Alvium 1800 U-158. I downloaded the SDK file and installed the drivers. The camera is detected and works properly when I use  Vimba X viewer. 

I tried different variations of managerName and cameraListIndex in the config file, but I still don't get where the issue comes from and how to solve it.

![mocker loaded](https://github.com/openUC2/ImSwitchConfig/assets/83556140/331f5d38-69f8-4487-b5cc-54f8e0e5828c)

I'm using the following configurations.

{
  "rs232devices": {
    "ESP32": {
      "managerName": "ESP32Manager",
      "managerProperties": {
        "host_": "192.168.43.129",
        "serialport": "COM9",
        "serialport_mac": "/dev/cu./dev/cu.SLAB_USBtoUART"
      }
    }
  },
  "positioners": {
    "ESPStage": {
        "managerName": "ESP32StageManager",
        "managerProperties": {
            "rs232device": "ESP32"
        },
        "axes": ["X", "Y", "Z"],
        "forScanning": true,
        "forPositioning": true
    }
},
"lasers":{
"635 Laser": {
  "analogChannel": null,
  "digitalLine": null,
  "managerName": "ESP32LEDLaserManager",
  "managerProperties": {
      "rs232device": "ESP32",
      "channel_index": 1, 
      "filter_change": false
  },
  "wavelength": 635,
  "valueRangeMin": 0,
  "valueRangeMax": 255
},
"LED": {
  "analogChannel": null,
  "digitalLine": null,
  "managerName": "ESP32LEDLaserManager",
  "managerProperties": {
      "rs232device": "ESP32",
      "channel_index": "LED", 
      "filter_change": false
  },
  "wavelength": 0,
  "valueRangeMin": 0,
  "valueRangeMax": 255
}
},
"detectors": {
  "WidefieldCamera": {
    "analogChannel": null,
    "digitalLine": null,
    "managerName": "TISManager",
    "managerProperties": {
      "cameraListIndex": 0,
      "tis": {
        "exposure": 0,
        "gain": 0,
        "blacklevel": 100,
        "image_width": 1000,
        "image_height": 1000
      }
    },
    "forAcquisition": true,
    "forFocusLock": true
  }
},
"rois": {
  "Full chip": {
    "x": 600,
    "y": 600,
    "w": 1200,
    "h": 1200
  }
},
  "availableWidgets": [
    "Settings",
    "View",
    "Recording",
    "Image",
    "Laser",
    "Positioner",
    "Autofocus"
  ],
  "autofocus": {
    "camera": "WidefieldCamera",
    "positioner": "ESP32Stage",
    "updateFreq": 10,
    "frameCropx": 780,
    "frameCropy": 400,
    "frameCropw": 500,
    "frameCroph": 100
  }
}

**Comment by beniroquai** [comment]
Please have a look here: https://openuc2.discourse.group/t/how-to-integrate-a-camera-into-imswitch/50/2
